version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPO_NAME:latest .
      - docker tag $REPO_NAME:latest $ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPO_NAME:latest